apply from: "config.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://developer.huawei.com/repo' }
        maven { url 'https://developer.hihonor.com/repo' }
    }
}

task clean(type: Delete) {
    delete rootProject.layout.buildDirectory
}
