plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion rootProject.ext.android.compileSdkVersion
    buildToolsVersion rootProject.ext.android.buildToolsVersion
    namespace = "com.yiman.ad.adbid"
    defaultConfig {
        applicationId "com.limo.adx"
        minSdkVersion rootProject.ext.android.minSdkVersion
        targetSdkVersion rootProject.ext.android.targetSdkVersion
        versionCode 20100019
        versionName "2.1.0.19"
    }

    signingConfigs {
        debug {
            storeFile file("./key/ydyFarm.keystore") // 密钥库文件路径
            storePassword "123456" // 密钥库密码
            keyAlias "aprilIdiom" // 密钥别名
            keyPassword "123456" // 0密钥密码
            enableV2Signing true
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            // 是否混淆
            minifyEnabled false
            // 混淆配置文件的位置
        }
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            // 混淆配置文件的位置
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {

    implementation(libs.androidx.core)
    implementation(libs.glide)
    implementation(libs.androidx.recyclerview)
    implementation(libs.play.services.ads.identifier)
    implementation(libs.play.services.location)
    implementation(libs.androidx.viewpager2)
    implementation(libs.androidx.appcompat)
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation(libs.androidx.constraintlayout)
    implementation 'com.geyifeng.immersionbar:immersionbar:3.2.2'

    //必选：领摩加载库
    implementation(files("libs/adbid_sdk_2.1.0.23_0901_1849.aar"))

    //必选：领摩核心库
    implementation(files("libs/adbid_limo_1.0.1_0623_1620.aar"))
    implementation(files("libs/adbid_lmx_1.0.0_0616_2311.aar"))
    //必选：领摩基础库
    implementation(files("libs/adbid_common_1.0.0_0616_2248.aar"))

    //选择性接入(强烈建议)：微信小程序,有利于提高收益
    implementation("com.tencent.mm.opensdk:wechat-sdk-android-without-mta:6.8.0")


}

