plugins {
    id 'com.android.application'
    id 'AndResGuard'
}

android {
    compileSdk rootProject.ext.android.compileSdkVersion
    namespace = "com.yiman.ad.adbid"
    defaultConfig {
        applicationId "com.limo.adx"
        minSdk rootProject.ext.android.minSdkVersion
        targetSdk rootProject.ext.android.targetSdkVersion
        versionCode 20100019
        versionName "2.1.0.19"
    }

    signingConfigs {
        debug {
            storeFile file("./key/ydyFarm.keystore")
            storePassword "123456"
            keyAlias "aprilIdiom"
            keyPassword "123456"
            enableV2Signing true
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

andResGuard {
    use7zip = false
    useSign = true
    keepRoot = false
    mergeDuplicatedRes = true
    whiteList = [
            "R.mipmap.ic_launcher",
            "R.mipmap.ic_launcher_round",
            "R.string.app_name",
            "R.style.Theme_AdBid",
            "R.anim.limo_*",
            "R.attr.limo_*",
            "R.color.limo_*",
            "R.dimen.limo_*",
            "R.drawable.limo_*",
            "R.id.limo_*",
            "R.layout.limo_*",
            "R.raw.limo_*",
            "R.string.limo_*",
            "R.style.limo_*",
            "R.xml.limo_*",
    ]
    compressFilePattern = [
            "*.png",
            "*.jpg",
            "*.jpeg",
            "*.gif",
            "resources.arsc",
    ]
}

dependencies {
    implementation(libs.androidx.core)
    implementation(libs.glide)
    implementation(libs.androidx.recyclerview)
    implementation(libs.play.services.ads.identifier)
    implementation(libs.play.services.location)
    implementation(libs.androidx.viewpager2)
    implementation(libs.androidx.appcompat)
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation(libs.androidx.constraintlayout)
    implementation 'com.geyifeng.immersionbar:immersionbar:3.2.2'

    //必选：领摩核心库
    implementation(files("libs/adbid_sdk_2.1.0.22_0827_2027.aar"))

    //选择性接入(强烈建议)：微信小程序,有利于提高收益
    implementation("com.tencent.mm.opensdk:wechat-sdk-android-without-mta:6.8.0")
}
